import { test, expect } from '@playwright/test';

test.describe('Course Forum App', () => {
  test('should redirect to login if not authenticated', async ({ page }) => {
    // Attempt to visit dashboard without logging in
    await page.goto('/');
    
    // Ensure we are redirected to the login page
    await expect(page).toHaveURL(/\/login/);
    await expect(page.getByText('Login')).toBeVisible();
    await expect(page.getByText('Select a user to continue.')).toBeVisible();
  });

  test('should login, view feed, and create a post', async ({ page }) => {
    // 1. Go to login page
    await page.goto('/login');

    // Wait for the mock users to load from the API
    await page.waitForSelector('button:has-text("Alice Student")');
    
    // 2. Select a user to login
    await page.click('button:has-text("Alice Student")');

    // 3. Ensure we are redirected to the dashboard (feed)
    await expect(page).toHaveURL('/');
    
    // 4. Verify dashboard elements
    await expect(page.getByText('Course Discussions')).toBeVisible();
    await expect(page.getByText('Logout')).toBeVisible();

    // 5. Test Creating a Post
    const newPostTitle = 'My First Automated Post';
    const newPostContent = 'This is content generated by a Playwright E2E test.';
    
    // Open the create post accordion/form
    await page.click('button:has-text("Create New Post")');

    // Select the first course in the dropdown
    await page.locator('select').selectOption({ index: 1 });

    // Fill in the form
    await page.fill('input[placeholder="What is on your mind?"]', newPostTitle);
    await page.fill('textarea[placeholder="Write your post here..."]', newPostContent);
    await page.click('button:has-text("Publish")');

    // Wait for the new post to appear in the feed
    await expect(page.getByText(newPostTitle)).toBeVisible();
    await expect(page.getByText(newPostContent)).toBeVisible();
    
    // 6. Test Save and Unsave functionality
    // Grab the first Save button on the screen
    const saveButton = page.locator('button:has-text("Save")').first();
    await expect(saveButton).toBeVisible();
    await saveButton.click();
    
    // Wait for it to become 'Saved'
    const savedButton = page.locator('button:has-text("Saved")').first();
    await expect(savedButton).toBeVisible();

    // 7. Test Like functionality
    const likeButton = page.locator('button:has-text("Like")').first();
    if (await likeButton.isVisible()) {
      await likeButton.click();
      await expect(page.locator('button:has-text("Liked")').first()).toBeVisible();
    }

    // 8. Test Commenting
    // Navigate to post details page
    const postLink = page.locator(`text=${newPostTitle}`).first();
    await postLink.click();
    
    // Ensure we are on the post page
    await expect(page).toHaveURL(/\/post\/.+/);

    // Add a comment
    const commentInput = page.locator('input[placeholder="Write a comment..."]');
    if (await commentInput.isVisible()) {
      await commentInput.fill('This is a test comment from Playwright.');
      await page.click('button:has-text("Comment")');
      // Verify comment appeared
      await expect(page.getByText('This is a test comment from Playwright.')).toBeVisible();
    }

    // Go back to feed
    await page.click('text=Back to Feed');

    // 9. Verify it appears in Saved Posts
    await page.click('text=Saved Posts');
    await expect(page).toHaveURL(/\/saved/);
    
    // We expect at least one post card in the saved view
    const savedCards = page.locator('.border.rounded-xl');
    expect(await savedCards.count()).toBeGreaterThan(0);

    // Unsave it from the saved page
    await savedButton.click();
    await expect(saveButton).toBeVisible();
  });
});
